# Generated by Django 4.2.15 on 2024-12-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0003_remove_userprogress_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='completed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
