# Generated by Django 4.2.15 on 2024-12-17 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0003_remove_userprogress_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='completed_workouts',
            field=models.ManyToManyField(blank=True, related_name='completed_by', to='machine_learning.workout'),
        ),
    ]
