# Generated by Django 4.2.15 on 2024-12-02 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0004_userprogress_completed_time_userprogress_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogress',
            name='completed_time',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='start_time',
        ),
    ]
