# Generated by Django 4.2.15 on 2024-12-17 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0005_remove_userprogress_completed_workouts_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userworkoutsession',
            options={'verbose_name_plural': 'Workout Sessions'},
        ),
    ]
