# Generated by Django 4.2.15 on 2025-01-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0006_alter_userworkoutsession_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='progress_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
