# Generated by Django 4.2.15 on 2024-12-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0007_remove_userprogress_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='progress_target_30_days',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_days_per_week',
            field=models.IntegerField(default=0),
        ),
    ]
