# Generated by Django 4.2.15 on 2024-12-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0008_userprofile_last_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='workouts_completed',
            field=models.IntegerField(default=0),
        ),
    ]
