# Generated by Django 4.2.15 on 2024-12-05 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0009_remove_userprofile_last_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='progress_target_30_days',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='target_days_per_week',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='workouts_completed',
        ),
    ]
