# Generated by Django 4.2.15 on 2024-12-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0011_completedworkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='time_spent',
            field=models.FloatField(default=0),
        ),
    ]
