# Generated by Django 4.2.15 on 2024-12-10 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('machine_learning', '0012_userprogress_time_spent'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('time_spent', models.DurationField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine_learning.workout')),
            ],
            options={
                'verbose_name': 'Workout Session',
                'verbose_name_plural': 'Workout Sessions',
            },
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='time_spent',
        ),
        migrations.DeleteModel(
            name='CompletedWorkout',
        ),
    ]
