# Generated by Django 4.2.15 on 2024-12-10 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0013_workoutsession_remove_userprogress_time_spent_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkoutSession',
        ),
    ]
