# Generated by Django 4.2.15 on 2024-12-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0014_delete_workoutsession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprogress',
            options={},
        ),
        migrations.AddField(
            model_name='userprogress',
            name='time_spent',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='progress',
            field=models.FloatField(default=0),
        ),
    ]
