# Generated by Django 4.2.15 on 2024-11-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0016_userprofile_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Fitness_Goal',
            field=models.CharField(default='Weight_Loss', max_length=50),
        ),
    ]
