# Generated by Django 4.2.15 on 2024-12-10 19:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0016_userprogress_completed_userprogress_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_workouts', models.PositiveIntegerField(default=0)),
                ('total_time_minutes', models.PositiveIntegerField(default=0)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='machine_learning.userprofile')),
            ],
            options={
                'verbose_name': 'Progress Tracker',
                'verbose_name_plural': 'Progress Trackers',
            },
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_time_minutes', models.PositiveIntegerField()),
                ('actual_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('session_date', models.DateField(default=django.utils.timezone.now)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine_learning.userprofile')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine_learning.workout')),
            ],
            options={
                'verbose_name': 'Workout Session',
                'verbose_name_plural': 'Workout Sessions',
            },
        ),
        migrations.DeleteModel(
            name='UserProgress',
        ),
    ]
