# Generated by Django 4.2.15 on 2024-11-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0017_alter_userprofile_fitness_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Fitness_Goal',
            field=models.CharField(default='Weight_Loss', max_length=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Fitness_Type',
            field=models.CharField(default='Cardio_Fitness', max_length=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Level',
            field=models.CharField(default='Normal', max_length=5),
        ),
    ]
