# Generated by Django 4.2.15 on 2024-11-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0018_alter_userprofile_fitness_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Sex',
            field=models.CharField(max_length=5),
        ),
    ]
