# Generated by Django 4.2.15 on 2024-11-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0020_alter_userprofile_fitness_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Fitness_Goal',
            field=models.CharField(default='Weight_Loss', max_length=50),
        ),
    ]
