# Generated by Django 4.2.15 on 2024-11-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0021_alter_userprofile_fitness_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Diabetes',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Hypertension',
            field=models.CharField(default='No', max_length=10),
        ),
    ]
