# Generated by Django 4.2.15 on 2024-11-20 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0020_alter_userprofile_fitness_type_and_more copy'),
        ('machine_learning', '0022_alter_userprofile_diabetes_and_more'),
    ]

    operations = [
    ]
